image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - prepare
  - build

services:
  - docker:dind

install-deps:
  stage: prepare
  script:
    - npm install

build-image:
  image: docker:latest
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
